### ISSUE TITLE
server fails to start with public IP

### ISSUE THREAD

**Issue by zoecarver** [lunemec/python-chat#1]
I love this app!!! the only thing is when I try to run it using a public IP address it fail. I run `python server.py 146.148.113.172 5000` to start the server and I get this error:
`Traceback (most recent call last):
  File "server.py", line 193, in <module>
    ChatServer(sys.argv[1], sys.argv[2]).serve()
  File "server.py", line 30, in __init__
    self.server.bind((address, int(port)))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address`

thank you for your help!
-Zoe

**Comment by lunemec** [comment]
Can you post the output of `ip a`? Thank you.

Also I should warn you, this program is not production quality and nobody performed any kind of security analysis on it. Since you're trying to run it on public IP :)

Also how is the machine connected to internet?
